# -*- coding: utf-8 -*-
"""AIML Project Trial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OVtVtXSx34E474uqjCgf1pGX5p7KhpuJ
"""

import pandas as pd

data_frame=pd.read_csv('IMDB dataset.csv')

data_frame.head()

data_frame=data_frame.drop('Poster_Link',axis=1)
data_frame=data_frame.dropna()

data_frame.head()

dataframe=data_frame
dataframe['Movie score']=dataframe['Meta_score']*dataframe['IMDB_Rating']
dataframe=dataframe.drop('Meta_score',axis=1)
dataframe=dataframe.drop('IMDB_Rating',axis=1)
dataframe.head()

import matplotlib.pyplot as plt

plt.boxplot(dataframe['Movie score'])

data_frame['Certificate']=data_frame['Certificate'].replace('U/A','UA')

data_frame['Certificate'].unique()

from tensorflow.keras.preprocessing.text import one_hot

voc_size=10000
#vocabulary size

sentences=data_frame['Overview']
one_hot_rep=[one_hot(words,voc_size)for words in sentences]
print(one_hot_rep)

print(len(one_hot_rep))

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

import numpy as np

temp_lst=data_frame['Overview']
print(temp_lst)

import string

another_lst=[]
for i in temp_lst:
  s = i.translate(str.maketrans('', '', string.punctuation))
  another_lst.append(s)

data_frame['Overview']=another_lst

data_frame['Overview'].head()

lst=[]
for i in data_frame['Overview']:
  lst.append(len(i))

sent_length=50

sentences=data_frame['Overview']
one_hot_rep=[one_hot(words,voc_size)for words in sentences]
print(one_hot_rep)

embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)

dim=15
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

temp=model.predict(embedded_docs)
print(temp)

len(temp[0][0])

lst2=[]
sum=0
for vals in temp:
  lst1=[]
  for subvals in vals:
    sum=0
    for furthersuvals in subvals:
      sum+=furthersuvals
    lst1.append(sum)
  lst2.append(lst1)

data_frame['Overview']=lst2

data_frame['Overview'].head()

data_frame.head()

directorArray=data_frame['Director'].unique()

print(directorArray.size)

name='harsh'
for char in name:
 print(ord(char))

director_list=data_frame['Director']
director_list_num=[]
for directors in director_list:
  temp=0
  for char in directors:
    if char != ' ':
      #converting the characters in director name into number
      #ord(char) converts the string character into its associated ascii value
      #adding the ascii values of characters present into name excpet for blankspace
      temp+=ord(char)
  director_list_num.append(temp)

director_list=data_frame['Director']
director_list_num=[]
for directors in director_list:
  temp=0
  for char in directors:
    if char != ' ':
      #converting the characters in director name into number
      #ord(char) converts the string character into its associated ascii value
      #adding the ascii values of characters present into name excpet for blankspace
      temp+=ord(char)
  director_list_num.append(temp)

matrix=dataframe.corr()
print(matrix)

star1_list=data_frame['Star1']
star1_list_num=[]
for stars in star1_list:
  temp=0
  for char in stars:
    if char != ' ':
      #converting the characters in director name into number
      #ord(char) converts the string character into its associated ascii value
      #adding the ascii values of characters present into name excpet for blankspace
      temp+=ord(char)
  star1_list_num.append(temp)

star2_list=data_frame['Star2']
star2_list_num=[]
for stars in star2_list:
  temp=0
  for char in stars:
    if char != ' ':
      #converting the characters in director name into number
      #ord(char) converts the string character into its associated ascii value
      #adding the ascii values of characters present into name excpet for blankspace
      temp+=ord(char)
  star2_list_num.append(temp)

star3_list=data_frame['Star3']
star3_list_num=[]
for stars in star3_list:
  temp=0
  for char in stars:
    if char != ' ':
      #converting the characters in director name into number
      #ord(char) converts the string character into its associated ascii value
      #adding the ascii values of characters present into name excpet for blankspace
      temp+=ord(char)
  star3_list_num.append(temp)

star4_list=data_frame['Star4']
star4_list_num=[]
for stars in star4_list:
  temp=0
  for char in stars:
    if char != ' ':
      #converting the characters in director name into number
      #ord(char) converts the string character into its associated ascii value
      #adding the ascii values of characters present into name excpet for blankspace
      temp+=ord(char)
  star4_list_num.append(temp)

dataframe=pd.DataFrame()
dataframe=data_frame

dataframe.head()

cer_list=data_frame['Certificate']
cer_list_num=[]
for stars in cer_list:
  temp=0
  for char in stars:
    if char != ' ':
      #converting the characters in director name into number
      #ord(char) converts the string character into its associated ascii value
      #adding the ascii values of characters present into name excpet for blankspace
      temp+=ord(char)
  cer_list_num.append(temp)

print(cer_list_num)

