# -*- coding: utf-8 -*-
"""H036 AIML Lab 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qhldwta0dxdc-x9BiJS4351uJE8BM4Y7

Aim: Wite a python/matlab program to generete the oouput of logical XOR function using Mc-Cullock pitts neuron
"""

###########################################################################################
#Harsh Pandit
#getting the inputs
def get_input():
  input1=int(input('Enter the first input in 1 or 0: '))
  input2=int(input('Enter the first input in 1 or 0: '))
  return input1,input2
#defining the activation fuction
def activation_function(theta,yin):
  if yin>=theta:
    return 1
  elif yin<theta:
    return 0
#defining the McCullocl Pitts model

def x1x2_(x1,x2,weight):
  w1=weight
  w2=-weight
  yin=(w1*x1)+(w2*x2)
  theta=weight
  yout1=activation_function(theta,yin)
  return yout1

def x2x1_(x1,x2,weight):
  w2=weight
  w1=-weight
  yin=(w1*x1)+(w2*x2)
  theta=weight
  yout2=activation_function(theta,yin)
  return yout2
#Logical OR function

def x1x2_x2x1_(x1,x2,weight):
  w2=weight
  w1=weight
  yin=(w1*x1)+(w2*x2)
  theta=weight
  yout=activation_function(theta,yin)
  return yout

x1,x2=get_input()
#checking whether the values are accetable or not
accepted_values=(0,1)#list of binary values
while (x1 not in accepted_values or x2 not in accepted_values):
  print('Please enter the input in terms of 1 or 0')
  x1,x2=get_input()
#getting the value of weight
weight=1
yout1=x1x2_(x1,x2,weight)
yout2=x2x1_(x1,x2,weight)
yout=x1x2_x2x1_(yout1,yout2,weight)
print('{} is the output for the inputs {} and {}'.format(yout,x1,x2))

