# -*- coding: utf-8 -*-
"""H036 AIML Lab 10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vd06oIAhjUT2XFcPh3AoE01YoexoPwr3
"""

#importing all relevant packages
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np

df=pd.read_excel('H036 Harsh Pandit AIML lab 10.xlsx')
print(df)

#splitting the data into training and testing
x=df[['Age']]
y=df[['Have Insurance']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

#defining the logistic model
logistic_model=LogisticRegression()
#fitting the training data into the model
logistic_model.fit(x_train,y_train)
#predicting the values using testing data
y_pred=logistic_model.predict(x_test)
#finding out the accuracy of the model
acc=logistic_model.score(x_test,y_test)
#printing the value of accuracy
print('The accuracy of the logistics model is: {}'.format(acc))

#######################################################################################


#H036 Harsh Pandit
#importing all relevant packages
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np
df=pd.read_excel('H036 Harsh Pandit AIML lab 10.xlsx')
print(df)
#splitting the data into training and testing
x=df[['Age']]
y=df[['Have Insurance']]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)
#defining the logistic model
logistic_model=LogisticRegression()
#fitting the training data into the model
logistic_model.fit(x_train,y_train)
#predicting the values using testing data
y_pred=logistic_model.predict(x_test)
#finding out the accuracy of the model
acc=logistic_model.score(x_test,y_test)
#printing the value of accuracy
print('The accuracy of the logistics model is: {}'.format(acc))

df1=pd.DataFrame()

df1['x_train']=x_test
df1['y_test']=y_test
df1['y_predict']=y_pred

df1

